import { StyleSheet } from 'react-native';

// Define all box styles
export const Boxes = StyleSheet.create({
    formBox:{
        display:'flex',
        flexDirection:'column',
        margin:20,
        paddingVertical:20,
        paddingHorizontal:40,
        gap:20,
        backgroundColor:'#111827',
        borderRadius:10,
    },
    formBox2:{
        display:'flex',
        flexDirection:'column',
        margin:20,
        paddingVertical:20,
        paddingHorizontal:20,
        gap:20,
        backgroundColor:'#111827',
        borderRadius:10,
    },
    textImputBox:{
        backgroundColor:'#000000',
        padding:15,
        borderRadius:5,
    },
    button:{
        display:'flex',
        backgroundColor:'#3997fbff',
        padding:15,
        borderRadius:10,
        textAlign:'center',
        justifyContent:'center',
        alignItems:'center'
    },
    button2:{
        display:'flex',
        backgroundColor:'#1F2937',
        padding:15,
        borderRadius:10,
        textAlign:'center',
        justifyContent:'center',
        alignItems:'center'
    },
    checkBox:{
        width:30,
        height:30,
        borderWidth:2,
        borderColor:'#FFFFFF',
        borderRadius:5,
    }
});